// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClMFZxbgseI4qF_moIby5A5JnGqp5PIQc',
    appId: '1:385248161061:web:c3a1a60f0f94f18649fecc',
    messagingSenderId: '385248161061',
    projectId: 'mwf-firebase',
    authDomain: 'mwf-firebase.firebaseapp.com',
    storageBucket: 'mwf-firebase.appspot.com',
    measurementId: 'G-0RY7CESDEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9hACJIwhpqFMGFO3oTFrIlOhZjIeYk8U',
    appId: '1:385248161061:android:1df45a67f5b6b74449fecc',
    messagingSenderId: '385248161061',
    projectId: 'mwf-firebase',
    storageBucket: 'mwf-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0BkiDNx96wBHjEn0U722dLKvGRVYzoZE',
    appId: '1:385248161061:ios:4b3498fb541510cc49fecc',
    messagingSenderId: '385248161061',
    projectId: 'mwf-firebase',
    storageBucket: 'mwf-firebase.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0BkiDNx96wBHjEn0U722dLKvGRVYzoZE',
    appId: '1:385248161061:ios:c562d4a1929b49a849fecc',
    messagingSenderId: '385248161061',
    projectId: 'mwf-firebase',
    storageBucket: 'mwf-firebase.appspot.com',
    iosBundleId: 'com.example.firebaseProject.RunnerTests',
  );
}
