// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiCx-SDsaZCNyhtlBSdNtINGbzlhjWijA',
    appId: '1:603120962485:web:dc590e80166883cb3627fc',
    messagingSenderId: '603120962485',
    projectId: 'fir-mwf-b0a87',
    authDomain: 'fir-mwf-b0a87.firebaseapp.com',
    storageBucket: 'fir-mwf-b0a87.appspot.com',
    measurementId: 'G-1RJVC5WFKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3KmwngJwfY_Lz6P7kfGKSiMIXYfoq4Po',
    appId: '1:603120962485:android:0d8d83b9393ee24a3627fc',
    messagingSenderId: '603120962485',
    projectId: 'fir-mwf-b0a87',
    storageBucket: 'fir-mwf-b0a87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAHuAK1jNJRmDk7Nq64zaMvTMIJn7Hc6w',
    appId: '1:603120962485:ios:daeea9fa61ee29c43627fc',
    messagingSenderId: '603120962485',
    projectId: 'fir-mwf-b0a87',
    storageBucket: 'fir-mwf-b0a87.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAHuAK1jNJRmDk7Nq64zaMvTMIJn7Hc6w',
    appId: '1:603120962485:ios:1d4276b00c8380bc3627fc',
    messagingSenderId: '603120962485',
    projectId: 'fir-mwf-b0a87',
    storageBucket: 'fir-mwf-b0a87.appspot.com',
    iosBundleId: 'com.example.firebaseProject.RunnerTests',
  );
}
